### ISSUE TITLE
TypeError: Int cannot represent non-integer value: 

### ISSUE THREAD

**Issue by rodbs** [panter/ra-data-prisma#19]
**What you were expecting:**

Retrieve a post for editing  after configuring ra-data-prisma ( `addCrudResolvers('Post')` ...)

**What happened instead:**

Instead, I keep getting a 400 Bad Request because it sends the id as a String instead of as an Integer
`{"errors":[{"message":"Variable \"$where\" got invalid value \"32\" at \"where.id\"; Expected type Int. Int cannot represent non-integer value: \"32\"","locations":[{"line":1,"column":12}]}]}`

This is the request payload
```
operationName: "post"
query: "query post($where: PostWhereUniqueInput!) {
  data: post(where: $where) {
     id
     published 
     title
     content
    __typename
 }
}"
variables: {
 where: {
   id: "32"
}}
 

```

**Steps to reproduce:**

Just try to edit any resource in react-admin (user, post ...) where it needs to send a graphql query  by id to prisma.

**Environment**

    React-admin version: 3.6

**Comment by macrozone** [comment]
@rodbs can you also mention your prisma version?

seems like int ids don't get properly parsed / formatted. string ids work correctly.
i will fix that and add a test case for int ids.


having said that: 

I advice against using integers as ids in general. Reasoning is

- integers are guessable, so you have to take extra care that you prevent "Insecure Direct Object Reference". This can be a security issue. Take a look at the [OWASP cheatshee](https://cheatsheetseries.owasp.org/cheatsheets/Insecure_Direct_Object_Reference_Prevention_Cheat_Sheet.html) 
- strings can represent integers, but not the other way around. So you can still use numbers even if you have string ids (like "1234"), but you can migrate eventually to any string pattern
- also ranges of integers can be platform dependent

_Some personal anecdote:_ in my early days as a programmer, we made an ipad app for a newspaper. I wrote the backend someone else wrote the app. We imported articles from some newspaper editor tool. These articles where in xml format and had some number as id:

```
<article id="4358282">...</article>
```

The app developer stored all downloaded articles in a database and used integers as ids. 
The app worked for some time but suddenly broke. It took us some time to realize that these "integers" in the xml exceeded the limit of an integer for that app database! We were in trouble: We could not update neither the app nor the backend without breaking some versions. So I had to encode the ids in the backend into another from of id. Could i find a transformation that would not collide with already existing ids? The transformation had also to be idempotent: there were links to these articles that needed to stay intact.

This would not have been a problem at all if we'd used a string to represent one article, even if they looked like numbers.

Since then i always use strings as ids, especially if you cross system boundaries through an api for example. Consider ids as something opaque: the content itself does not matter, there should be no information in the id but the fact that two different ids are different objects. 

I therefore strongly advice to use uuids for ids. 

in prisma you can use this:

```
  id              String           @default(uuid()) @id
```

you can also use  `cuid()` instead [click here for more information](https://hashnode.com/post/what-is-the-difference-between-cuid-and-uuid-cilkdlykh005djz53hticmc58)

**Comment by endorphin82** [comment]
i have is problem if call Edit component <Edit title="Edit product" { ...props, id: +props.id }>...<Edit/>

fix for me <Edit title="Edit product" {...{ ...props, id: +props.id }}>

**Comment by rodbs** [comment]
# #@macrozone 

I'm using the stable version of Prisma released last week (2.0.0).
I've applied the suggestion of using strings for ids and it works! Thanks!

**Comment by rodbs** [comment]
@macrozone 

I'm using the stable version of Prisma released last week (2.0.0).
I've applied the suggestion of using strings for ids and it works! Thanks!
(sorry for the mess with the comments!)

**Comment by macrozone** [comment]
@rodbs nevertheless, i fixed the problem that it would try to pass integers as strings to the query in case its a int-id.

but i did not test it in a real world app, just wrote a test against. 

i will merge it in version 2 nevertheles, maybe you can try it out if you still want to use ints as ids ;-) (altough i would not)

By the way, as you use prisma version 2, you will need to use version 2.0.0 of these packages here, they are not under stable tag yet, but under next tag. But i think i will release them as stable now.

Only problem is that you need to use https://github.com/graphql-nexus/nexus-schema-plugin-prisma 0.15.0-next.x as well, which is also not yet released as "stable"

I assume that you used both next versions? otherwise pagination will not work ;-)

**Comment by rodbs** [comment]
@macrozone 
I've updated all the packages (@prisma/client : " 2.0.1",, @ra-data-prisma/backend: " 2.0.1,  and nexus-prisma to 0.15.)
.

Mostly, after upgrading nexus-prisma, now I'm getting all these errors I didn't have yesterday (after using id as strings with the nexus-prisma 0.14 worked fine)
I'm not using t.crud anywhere.

```

C:\igls\igls1-back\node_modules\@nexus\schema\dist\utils.js:262
        throw new Error("\n" + errors);
        ^

Error:
- Missing type UserWhereInput, did you forget to import a type to the root query?
- Missing type UserOrderByInput, did you forget to import a type to the root query?
- Missing type UserWhereUniqueInput, did you forget to import a type to the root query or mean TableLineEngSpaWhereUniqueInput?
- Missing type PostWhereInput, did you forget to import a type to the root query?
- Missing type PostOrderByInput, did you forget to import a type to the root query?
- Missing type PostWhereUniqueInput, did you forget to import a type to the root query or mean TableLineEngSpaWhereUniqueInput?

```




By the way, these nexus packages are quite confusing. There are this 2 repositories
https://github.com/graphql-nexus/nexus-plugin-prisma
https://github.com/graphql-nexus/nexus-schema-plugin-prisma

What are the differences?  
I'm using nexus-schema-plugin-prisa (nexus-prisma), but I've read in the other it comes with the prisma CLI included ....
Where can I learn more about it? Are there any best practice to follow?

Thanks!

**Comment by rodbs** [comment]
I've fixed it using:
```
  plugins: [nexusPrismaPlugin({
      experimentalCRUD: true,
    })],
```
